apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: network-test
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: stefanprodan/podinfo:6.9.0
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: network-test
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 9898
