apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: network-test
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: stefanprodan/podinfo:6.9.0
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: network-test
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 9898
