apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: network-test
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: stefanprodan/podinfo:6.9.0
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: network-test
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 9898
