apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend-system
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: stefanprodan/podinfo:6.9.0
        ports:
        - containerPort: 9898
