apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-storage
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app: node-storage
    includeSelectors: true
    includeTemplates: true
