apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: critical-app
        image: busybox
        command:
        - "sh"
        args:
        - "-c"
        - "while true; do echo \"[$(date)] doing critical work...\" > /var/log/critical-app.log; sleep 10; done"
