apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: [scenario-namespace]
resources:
  - namespace.yaml
  # Add other resources as needed
labels:
  - pairs:
      key: value
    includeSelectors: true
    includeTemplates: true
