apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - deployment.yaml
labels:
  - pairs:
      app: critical-app
    includeSelectors: true
    includeTemplates: true
