apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 10
  template:
    spec:
      containers:
      - name: webapp
        image: stefanprodan/podinfo:6.8.0
        ports:
        - containerPort: 9898
        startupProbe:
          httpGet:
            path: /healthz
            port: 9898
