apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer
resources:
  - namespace.yaml
labels:
  - pairs:
      app: developer-app
      component: developer
    includeSelectors: true
    includeTemplates: true
