apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auditor/
  - developer/
labels:
  - pairs:
      scenario: service-account-troubleshooting
    includeSelectors: true
    includeTemplates: true
